/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UserStoryController;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.AssignedStory;
import model.Story;

/**
 *
 * @author Radical
 */
public class ViewFeedback extends javax.swing.JPanel {

    private UserStoryController usc = null;
    private Story _story;

    /**
     * Creates new form ViewFeedback
     */
    public ViewFeedback() {
        initComponents();

        usc = new UserStoryController();
        try {
            LinkedList<AssignedStory> assignedStories = usc.getAssignedChidrenToStory(this.getStory().getId(), false);
            
            

        } catch (Exception ex) {
            Logger.getLogger(ViewFeedback.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        totalFeedbackLabel = new javax.swing.JLabel();
        happyLabel = new javax.swing.JLabel();
        sadLabel = new javax.swing.JLabel();
        madLabel = new javax.swing.JLabel();
        confusedLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 650));

        btnClose.setText("Close");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Feedback for story : \" Story Name Here\"");

        totalFeedbackLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalFeedbackLabel.setText("Total Feedback: ");

        happyLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        happyLabel.setText("Happy:");

        sadLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sadLabel.setText("Sad:");

        madLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        madLabel.setText("Mad:");

        confusedLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confusedLabel.setText("Confused:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalFeedbackLabel)
                    .addComponent(confusedLabel)
                    .addComponent(madLabel)
                    .addComponent(sadLabel)
                    .addComponent(happyLabel))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(happyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(madLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confusedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalFeedbackLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClose)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel confusedLabel;
    private javax.swing.JLabel happyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel madLabel;
    private javax.swing.JLabel sadLabel;
    private javax.swing.JLabel totalFeedbackLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the _story
     */
    public Story getStory() {
        return _story;
    }

    /**
     * @param story the _story to set
     */
    public void setStory(Story story) {
        this._story = story;
    }
}
