/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UserStoryController;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import model.AssignedStory;
import model.Feedback;
import model.Story;

/**
 *
 * @author Radical
 */
public class ViewFeedback extends javax.swing.JPanel {

    private UserStoryController usc = null;
    private Hashtable<String, Integer> feedbacks;

    /**
     * Creates new form ViewFeedback
     *
     * @param story The story to view feedback
     */
    public ViewFeedback(Story story) {
        initComponents();
        feedbacks = new Hashtable<>();
        feedbacks.put(Feedback.CONFUSED.toString(), 0);
        feedbacks.put(Feedback.HAPPY.toString(), 0);
        feedbacks.put(Feedback.SAD.toString(), 0);
        feedbacks.put(Feedback.MAD.toString(), 0);

        if (story != null) {
            lblStoryName.setText(lblStoryName.getText() + story.getTitle());

            usc = new UserStoryController();
            try {
                LinkedList<AssignedStory> assignedStories = usc.getAssignedChidrenToStory(story.getId(), false);

                if (assignedStories != null && !assignedStories.isEmpty()) {
                    for (AssignedStory as : assignedStories) {
                        int fbCount = 0;

                        if (as.isDone()) {
                            if ((as.getFeedback() != null) && (!as.getFeedback().equals(""))) {
                                fbCount = feedbacks.get(as.getFeedback());
                                fbCount = fbCount + 1;
                            }
                        }

                        feedbacks.put(as.getFeedback(), fbCount);
                        System.out.println(as.getFeedback() + " " + feedbacks.get(as.getFeedback()));
                    }

                    madLabel.setText(madLabel.getText() + " " + feedbacks.get(Feedback.MAD.toString()));
                    confusedLabel.setText(confusedLabel.getText() + " " + feedbacks.get(Feedback.CONFUSED.toString()));
                    happyLabel.setText(happyLabel.getText() + " " + feedbacks.get(Feedback.HAPPY.toString()));
                    sadLabel.setText(sadLabel.getText() + " " + feedbacks.get(Feedback.SAD.toString()));

                    int total = 0;
                    for(Integer f : feedbacks.values()) {
                        total += f;
                    }
                    
                    totalFeedbackLabel.setText(totalFeedbackLabel.getText() + total);
                }
            } catch (Exception ex) {
                Logger.getLogger(ViewFeedback.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        lblStoryName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        totalFeedbackLabel = new javax.swing.JLabel();
        happyLabel = new javax.swing.JLabel();
        sadLabel = new javax.swing.JLabel();
        madLabel = new javax.swing.JLabel();
        confusedLabel = new javax.swing.JLabel();

        setPreferredSize(null);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblStoryName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStoryName.setText("Feedback for story:  ");

        totalFeedbackLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalFeedbackLabel.setText("Total Feedback: ");

        happyLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        happyLabel.setText("Happy:");

        sadLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sadLabel.setText("Sad:");

        madLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        madLabel.setText("Mad:");

        confusedLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confusedLabel.setText("Confused:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalFeedbackLabel)
                    .addComponent(confusedLabel)
                    .addComponent(madLabel)
                    .addComponent(sadLabel)
                    .addComponent(happyLabel))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(happyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(madLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confusedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalFeedbackLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClose)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(lblStoryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
        dialog.dispose();
        dialog.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel confusedLabel;
    private javax.swing.JLabel happyLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStoryName;
    private javax.swing.JLabel madLabel;
    private javax.swing.JLabel sadLabel;
    private javax.swing.JLabel totalFeedbackLabel;
    // End of variables declaration//GEN-END:variables
}
